######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 28 17:07:01 2012
######################################################################

CONFIG += qt
TEMPLATE = app
TARGET = Compositor
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += compositor.h timer.h
FORMS += compositor.ui
SOURCES += compositor.cpp main.cpp
RESOURCES += compositor.qrc
