######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 23 16:59:05 2012
######################################################################

CONFIG += qt
TEMPLATE = app
TARGET = Compositor
DEPENDPATH += ../src
INCLUDEPATH += . ../src

# Input
HEADERS += ../src/compositor.h ../src/timer.h
FORMS += ../src/compositor.ui
SOURCES += ../src/compositor.cpp ../src/main.cpp
RESOURCES += ../src/compositor.qrc
